apiVersion: apps/v1
kind: Deployment
metadata:
  name: trgfvx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trgfvx
  template:
    metadata:
      labels:
        app: trgfvx
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: trgfvx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8468cd2d-236b-4430-be3d-73d427e57f4b"
        - name: Vless_Path
          value: "/vl0729"
        - name: Vmess_UUID
          value: "8468cd2d-236b-4430-be3d-73d427e57f4b"
        - name: Vmess_Path
          value: "/vm0729"
        - name: Share_Path
          value: "/v2link"
